version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: question_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  

  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"  
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin  

volumes:
  postgres_data:  
  pgadmin_data:   